/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/channel-analysis': RouteRecordInfo<'/channel-analysis', '/channel-analysis', Record<never, never>, Record<never, never>>,
    '/comparison': RouteRecordInfo<'/comparison', '/comparison', Record<never, never>, Record<never, never>>,
    '/external-analysis': RouteRecordInfo<'/external-analysis', '/external-analysis', Record<never, never>, Record<never, never>>,
    '/general-analysis': RouteRecordInfo<'/general-analysis', '/general-analysis', Record<never, never>, Record<never, never>>,
    '/industry-analysis': RouteRecordInfo<'/industry-analysis', '/industry-analysis', Record<never, never>, Record<never, never>>,
    '/internal-analysis': RouteRecordInfo<'/internal-analysis', '/internal-analysis', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/channel-analysis.vue': {
      routes: '/channel-analysis'
      views: never
    }
    'src/pages/comparison.vue': {
      routes: '/comparison'
      views: never
    }
    'src/pages/external-analysis.vue': {
      routes: '/external-analysis'
      views: never
    }
    'src/pages/general-analysis.vue': {
      routes: '/general-analysis'
      views: never
    }
    'src/pages/industry-analysis.vue': {
      routes: '/industry-analysis'
      views: never
    }
    'src/pages/internal-analysis.vue': {
      routes: '/internal-analysis'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
